# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import currency_pb2 as currency__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in currency_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CurrencyConverterStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/currencyconverter.CurrencyConverter/Convert',
                request_serializer=currency__pb2.ConversionRequest.SerializeToString,
                response_deserializer=currency__pb2.ConversionResponse.FromString,
                _registered_method=True)
        self.GetAvailableCurrencies = channel.unary_unary(
                '/currencyconverter.CurrencyConverter/GetAvailableCurrencies',
                request_serializer=currency__pb2.EmptyRequest.SerializeToString,
                response_deserializer=currency__pb2.CurrenciesResponse.FromString,
                _registered_method=True)
        self.GetExchangeRate = channel.unary_unary(
                '/currencyconverter.CurrencyConverter/GetExchangeRate',
                request_serializer=currency__pb2.ExchangeRateRequest.SerializeToString,
                response_deserializer=currency__pb2.ExchangeRateResponse.FromString,
                _registered_method=True)


class CurrencyConverterServicer(object):
    """Service definition
    """

    def Convert(self, request, context):
        """Convert from one currency to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableCurrencies(self, request, context):
        """Get all available currencies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchangeRate(self, request, context):
        """Get exchange rate between two currencies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=currency__pb2.ConversionRequest.FromString,
                    response_serializer=currency__pb2.ConversionResponse.SerializeToString,
            ),
            'GetAvailableCurrencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableCurrencies,
                    request_deserializer=currency__pb2.EmptyRequest.FromString,
                    response_serializer=currency__pb2.CurrenciesResponse.SerializeToString,
            ),
            'GetExchangeRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeRate,
                    request_deserializer=currency__pb2.ExchangeRateRequest.FromString,
                    response_serializer=currency__pb2.ExchangeRateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'currencyconverter.CurrencyConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('currencyconverter.CurrencyConverter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrencyConverter(object):
    """Service definition
    """

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/currencyconverter.CurrencyConverter/Convert',
            currency__pb2.ConversionRequest.SerializeToString,
            currency__pb2.ConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/currencyconverter.CurrencyConverter/GetAvailableCurrencies',
            currency__pb2.EmptyRequest.SerializeToString,
            currency__pb2.CurrenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExchangeRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/currencyconverter.CurrencyConverter/GetExchangeRate',
            currency__pb2.ExchangeRateRequest.SerializeToString,
            currency__pb2.ExchangeRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
