# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63urrency.proto\x12\x11\x63urrencyconverter\"\x0e\n\x0c\x45mptyRequest\"O\n\x11\x43onversionRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"\x99\x01\n\x12\x43onversionResponse\x12\x18\n\x10\x63onverted_amount\x18\x01 \x01(\x01\x12\x15\n\rfrom_currency\x18\x02 \x01(\t\x12\x13\n\x0bto_currency\x18\x03 \x01(\t\x12\x15\n\rexchange_rate\x18\x04 \x01(\x01\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\"A\n\x13\x45xchangeRateRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\"U\n\x14\x45xchangeRateResponse\x12\x15\n\rexchange_rate\x18\x01 \x01(\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"P\n\x12\x43urrenciesResponse\x12\x12\n\ncurrencies\x18\x01 \x03(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xb7\x02\n\x11\x43urrencyConverter\x12X\n\x07\x43onvert\x12$.currencyconverter.ConversionRequest\x1a%.currencyconverter.ConversionResponse\"\x00\x12\x62\n\x16GetAvailableCurrencies\x12\x1f.currencyconverter.EmptyRequest\x1a%.currencyconverter.CurrenciesResponse\"\x00\x12\x64\n\x0fGetExchangeRate\x12&.currencyconverter.ExchangeRateRequest\x1a\'.currencyconverter.ExchangeRateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=37
  _globals['_EMPTYREQUEST']._serialized_end=51
  _globals['_CONVERSIONREQUEST']._serialized_start=53
  _globals['_CONVERSIONREQUEST']._serialized_end=132
  _globals['_CONVERSIONRESPONSE']._serialized_start=135
  _globals['_CONVERSIONRESPONSE']._serialized_end=288
  _globals['_EXCHANGERATEREQUEST']._serialized_start=290
  _globals['_EXCHANGERATEREQUEST']._serialized_end=355
  _globals['_EXCHANGERATERESPONSE']._serialized_start=357
  _globals['_EXCHANGERATERESPONSE']._serialized_end=442
  _globals['_CURRENCIESRESPONSE']._serialized_start=444
  _globals['_CURRENCIESRESPONSE']._serialized_end=524
  _globals['_CURRENCYCONVERTER']._serialized_start=527
  _globals['_CURRENCYCONVERTER']._serialized_end=838
# @@protoc_insertion_point(module_scope)
